version: "3.3"

services:
    nextjs:
        container_name: nextjs
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - ./:/usr/src/app
            - node_modules
            - .next
        env_file:
            - ./env/system.env
